### ISSUE TITLE
 anic: key-value delimiter not found:

### ISSUE THREAD

**Issue by starpotion** [SrKomodo/shadowfox-updater#14] opened 2018-06-28 02:18 UTC
Opening either of the Windows exes in Command Prompt throws up this error:

C:\Users\rekyuu>"C:\Users\rekyuu\Downloads\shadowfox_windows_amd64.exe"
 anic: key-value delimiter not found:

goroutine 1 [running]:
main.getProfilePaths(0x729900, 0xc04214efc0, 0xc042075bf0, 0x4103f3, 0xc042078178, 0x8)
        /home/travis/gopath/src/github.com/SrKomodo/shadowfox-updater/profiles.go:57 +0x7f7
main.createUI(0xc042075f78, 0xc042048058)
        /home/travis/gopath/src/github.com/SrKomodo/shadowfox-updater/ui.go:23 +0x5b
main.main()
        /home/travis/gopath/src/github.com/SrKomodo/shadowfox-updater/main.go:4 +0x29

**Comment by SrKomodo** [comment] 2018-07-13 23:18
I'm not promising anything, but i think that the issue might have been fixed in the latest version. Please try it and inform me if it's still not working

**Comment by starpotion** [comment] 2018-07-16 23:49
Unfortunately, both binaries still give me the same error:

C:\Users\rekyuu\Downloads>shadowfox_windows_amd64.exe
 anic: key-value delimiter not found:

goroutine 1 [running]:
main.getProfilePaths(0x729900, 0xc04214efc0, 0xc042075bf0, 0x4103f3, 0xc042078170, 0x8)
        /home/travis/gopath/src/github.com/SrKomodo/shadowfox-updater/profiles.go:57 +0x7f7
main.createUI(0xc042075f78, 0xc042048058)
        /home/travis/gopath/src/github.com/SrKomodo/shadowfox-updater/ui.go:23 +0x5b
main.main()
        /home/travis/gopath/src/github.com/SrKomodo/shadowfox-updater/main.go:4 +0x29

C:\Users\rekyuu\Downloads>shadowfox_windows_386.exe
 anic: key-value delimiter not found:

goroutine 1 [running]:
main.getProfilePaths(0x6a5fc0, 0x134100f0, 0x1f, 0x134667e0, 0x3095700, 0x0)
        /home/travis/gopath/src/github.com/SrKomodo/shadowfox-updater/profiles.go:81 +0x8f1
main.createUI(0x134665a0, 0x133be1b0)
        /home/travis/gopath/src/github.com/SrKomodo/shadowfox-updater/ui.go:23 +0x41
main.main()
        /home/travis/gopath/src/github.com/SrKomodo/shadowfox-updater/main.go:6 +0x1a

**Comment by SrKomodo** [comment] 2018-07-17 02:07
hmm, does the issue still happen if you just double click it from the file explorer instead of running it from the command prompt?

Also, could you open `about:profiles` in firefox and tell me what is the root directory of your profile? It should say something like `C:\Users\[your user]\AppData\Roaming\Mozilla\Firefox\Profiles\[profile name]`

**Comment by starpotion** [comment] 2018-07-25 04:58
Hello, sorry about that. Running both exes (after telling SmartScreen to run them anyway) quickly flashes the Command Prompt but Firefox remains unchanged.

Also the root directory of my profile is located in: `C:\Users\rekyuu\AppData\Roaming\Mozilla\Firefox\Profiles\it9didja.default`

**Comment by Hawpe** [comment] 2018-07-25 20:04
Same problem here, screen flashes with a command prompt. Running the .exe in the command prompt gives the exact same error as @starpotion

**Comment by Hawpe** [comment] 2018-07-26 13:09
I managed to fix this error by taking a Firefox profiles.ini file from a linux system. Attached it if @starpotion wants to try.
Though now the problem is that the installer isn't even able to create the necessary folders, even if given administrator rights. Are you sure this is even compatible with Windows @SrKomodo ?

[profiles.zip](https://github.com/SrKomodo/shadowfox-updater/files/2232063/profiles.zip)
![image](https://user-images.githubusercontent.com/26039652/43264253-d2c8bfa8-90e5-11e8-8c4e-56d520999fdf.png)

**Comment by SrKomodo** [comment] 2018-07-26 16:55
@starpotion I think i figured out what the problem is. Can you [check](http://stackoverflow.com/questions/3710374/ddg#13464816) if profiles.ini is encoded in UTF-8? The same crash happened in #4 and in that case the solution was to change the encoding to UTF-8. I also have an issue open for this specific problem #6

v1.5.6 has better crash logs which should make this easier to figure out in the future

**Comment by starpotion** [comment] 2018-07-30 22:09
Changed the profile encoding and it works perfectly!

**Comment by SrKomodo** [comment] 2018-07-30 22:59
Nice!

**Closed by SrKomodo** 2018-07-30 22:59 UTC

**Comment by Vokuar** [comment] 2019-03-29 07:35
how does one change profile encoding

**Comment by SrKomodo** [comment] 2019-03-29 19:49
@Vokuar [here](http://stackoverflow.com/questions/3710374/ddg#13464816) is a simple how-to

**Comment by Vokuar** [comment] 2019-03-30 05:45
@SrKomodo thank you

**Comment by Vokuar** [comment] 2019-03-30 05:48
@SrKomodo and what file do I need to change

**Comment by SrKomodo** [comment] 2019-03-30 15:31
@Vokuar you need to change the `profiles.ini` file, you can find out where it is by going to `about:profiles` in firefox and opening the root folder
