### ISSUE TITLE
Doesn't find profile automatically under Win 8.1x64

### ISSUE THREAD

**Issue by stonecrusher** [SrKomodo/shadowfox-updater#4] opened 2018-04-24 10:10 UTC
Where I am supposed to put the .exe?
Even next to the `profiles.ini` it can't find it.

![screenshot 3](https://user-images.githubusercontent.com/1388389/39180047-2c679e40-47b6-11e8-9bbb-34956981c5c9.png)

When trying to copy and paste the path it is stripped at 11 characters, but this might be a windows issue.

`C:\Users\ad` instead of
`C:\Users\admin\AppData\Roaming\Mozilla\Firefox\profiles.ini`

shadowfox_windows_amd64.exe V1.40

**Comment by SavageCore** [comment] 2018-04-24 10:40
Same issue, well 2 issues: 
- [ ] Character stripping on paste
- [ ] Profile not found when full path given

I have tried running as admin in case it was a permission issue.

Windows 10 64 bit
FF 59.0.2

**Comment by SrKomodo** [comment] 2018-04-24 16:28
the pasting issue is a limitation with the library I'm using for the UI, so sadly it can't be fixed until the library fixes it

For the other issue i think that I'm just gonna rewrite the profile finding code for the next version.

Currently the directory the program is in doesn't matter, but I'm gonna make it so that if the program is on the same folder as profiles.ini it will use that folder

**Comment by SavageCore** [comment] 2018-04-24 23:05
Still seeing `panic: key-value delimiter not found:` error with 1.4.1. Doesn't even prompt for path anymore, is there a settings file I could clear?

**Comment by SrKomodo** [comment] 2018-04-24 23:09
Alright, now in v1.4.1 the program will go through these steps to find profiles.ini:
1. Check if profiles.ini is in the current directory
2. Try to auto-detect where profiles.ini is based on the default locations
3. If all else fails it will show you this following screen

![image](https://user-images.githubusercontent.com/22225222/39218357-aa6e7036-47fa-11e8-8fb0-d58bb8b80d22.png)

This fixes the pasting issue because, well, there isn't an input field to paste to

@SavageCore your error seems really weird, can you show me your `profiles.ini` file? I have a theory that it might be a problem with the parser for `profiles.ini`

**Comment by SavageCore** [comment] 2018-04-24 23:12
[profiles.txt](https://github.com/SrKomodo/shadowfox-updater/files/1944910/profiles.txt)

Changed to txt for GitHub.

**Comment by SrKomodo** [comment] 2018-04-24 23:16
Hmm, I'm pretty sure the file is okay so the problem might be somewhere else in the code. Can you paste the entire error that shows up in v1.4.1? (I want to be 100% sure the problem isn't the parser before trying something else)

**Comment by SavageCore** [comment] 2018-04-24 23:18
```
C:\Users\SavageCore\AppData\Roaming\Mozilla\Firefox>shadowfox_windows_amd64.exe
 anic: key-value delimiter not found:


goroutine 1 [running]:
main.getProfilePaths(0x7210c0, 0xc042146fc0, 0xc042004158, 0x8, 0x8, 0x6fde60)
        /home/travis/gopath/src/github.com/SrKomodo/shadowfox-updater/ui.go:226 +0x7f7
main.createUI()
        /home/travis/gopath/src/github.com/SrKomodo/shadowfox-updater/ui.go:45 +0x5b
main.main()
        /home/travis/gopath/src/github.com/SrKomodo/shadowfox-updater/main.go:4 +0x27
```

When double clicking I just get a quick flash of cmd window

**Comment by stonecrusher** [comment] 2018-04-24 23:25
Just to tell you, 1.41 autodetect works well on my end.

**Comment by SrKomodo** [comment] 2018-04-24 23:26
@stonecrusher Nice! So now all that is left to close this issue is to fix the parser problem

**Comment by SrKomodo** [comment] 2018-04-24 23:31
@SavageCore After taking a really close look to your file, I finally figured out the issue. Your file is encoded in `UTF-16 LE`, meanwhile the ini parser i'm using only supports `UTF-8`. I will try to either find a better parser or write one myself

**Comment by SavageCore** [comment] 2018-04-24 23:34
That's great! Converted to `UTF-8` in Notepad++ and I am all installed!

Auto-detect fine too.

**Closed** 2018-04-25 00:00 UTC
